<h1>Curso: <?= $curso->id ?>| <?= $curso->name ?></h1>

<ul class="h-menu">
    <li><a href="<?= URL ?>/cursos/tareas/<?= $curso->id ?>" title="Inicio" class="item ventas_index"> Tareas </a></li>
    <li><a href="<?= URL ?>/cursos/alumnos/<?= $curso->id ?>" title="Inicio" class="item ventas_index"> Alumnos </a></li>
    <li><a href="<?= URL, "/asistencia/pasa_lista/{$curso->id}/0/", date("Y-m-d") ?>" title="Asistencia" class="item "> Asistencia </a></li>
</ul>



