<?php View::partial("cursos/_menu", false, array("curso" => $curso)); ?>
<h3>Tareas</h3>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Curso</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($tareas as $t): ?>
        <tr>
             <td><?= $t->id ?></td>
            <td> <a href="/kamilo/cursos/calificar/<?= $curso_id,"/",$t->id ?>"><?= $t->title ?></a> </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
