<ul class="navview-menu mt-4" id="side-menu">
    <li class="item-header">MAIN NAVIGATION</li>
    <li>
        <a href="#dashboard">
            <span class="icon"><span class="mif-meter"></span></span>
            <span class="caption">Dashboard</span>
        </a>
    </li>
    <li>
        <a href="<?= URL ?>/cursos">
            <span class="icon"><span class="mif-widgets"></span></span>
            <span class="caption">Cursos</span>
        </a>
    </li>

</ul>
